# Form implementation generated from reading ui file 'ui\mainwindow.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(642, 600)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 1, 1, 1)
        self.studentsTable = QtWidgets.QTableWidget(parent=self.centralwidget)
        self.studentsTable.setGridStyle(QtCore.Qt.PenStyle.SolidLine)
        self.studentsTable.setObjectName("studentsTable")
        self.studentsTable.setColumnCount(3)
        self.studentsTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.studentsTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.studentsTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.studentsTable.setHorizontalHeaderItem(2, item)
        self.studentsTable.horizontalHeader().setDefaultSectionSize(200)
        self.studentsTable.horizontalHeader().setSortIndicatorShown(False)
        self.studentsTable.horizontalHeader().setStretchLastSection(False)
        self.studentsTable.verticalHeader().setSortIndicatorShown(False)
        self.studentsTable.verticalHeader().setStretchLastSection(False)
        self.gridLayout.addWidget(self.studentsTable, 1, 0, 1, 3)
        self.newEntryButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.newEntryButton.setObjectName("newEntryButton")
        self.gridLayout.addWidget(self.newEntryButton, 2, 0, 1, 1)
        self.saveButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.saveButton.setObjectName("saveButton")
        self.gridLayout.addWidget(self.saveButton, 2, 2, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 642, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Student-List"))
        item = self.studentsTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Vorname"))
        item = self.studentsTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Nachname"))
        item = self.studentsTable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Studienfach"))
        self.newEntryButton.setText(_translate("MainWindow", "Neuer Eintrag"))
        self.saveButton.setText(_translate("MainWindow", "Speichern"))
